import {
  GET_SUBJECT_BEGIN,
  GET_SUBJECT_SUCCESS,
  GET_SUBJECT_FAILURE,
  REMOVE_SUBJECT,
  CHANGE_SUBJECT_COLOR,
} from '../actionTypes';
import axios from 'axios';

const getSubjectBegin = (year, code, name, online) => ({
  type: GET_SUBJECT_BEGIN,
  payload: {year, code, name, online},
});

const getSubjectSuccess = (year, code, name, online, studyPeriod, classInfo) => ({
  type: GET_SUBJECT_SUCCESS,
  payload: {year, code, name, online, studyPeriod, classInfo},
});

const getSubjectFailure = (code, error) => ({
  type: GET_SUBJECT_FAILURE,
  payload: {code, error},
});

export const getSubject = (year, studyPeriod, code, name, online) => dispatch => {
  dispatch(getSubjectBegin(year, code, name, online, studyPeriod));
  const listURL = `/subject?year=${year}&period=${studyPeriod}&code=${code}`;

  return dispatch(getSubjectSuccess(year, code, name, online, studyPeriod, FAKE_DATA));

  return axios
    .get(listURL)
    .then(res => dispatch(getSubjectSuccess(year, code, name, online, studyPeriod, res.data)))
    .catch(err => dispatch(getSubjectFailure(code, err)));
};

export const changeSubjectColor = (year, studyPeriod, code, color) => dispatch => {
  dispatch({
    type: CHANGE_SUBJECT_COLOR,
    payload: {year, code, studyPeriod, color},
  });
};

export const removeSubject = code => ({
  type: REMOVE_SUBJECT,
  payload: {code},
});

export const FAKE_DATA = {
  code: 'MAST20004',
  period: 'semester_1',
  _classList: [],
  _irregularClasses: [],
  _mandatoryClasses: [],
  _regularClasses: [],
  _streamContainers: [
    {
      streams: [
        {
          type: 'L',
          classes: [
            {
              description: 'Lecture 1',
              day: 0,
              start: 15.25,
              finish: 16.25,
              weeks: [9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21],
              type: 'Stream',
              online: false,
              subjectCode: 'MAST20004',
              codes: ['MAST20004/U/1/SM1/L01/02'],
              locations: ['PAR-Redmond Barry-101 (Lyle Theatre)'],
              classCode: {
                number: 1,
                type: 'L',
              },
              streamNumber: 2,
            },
            {
              description: 'Lecture 2',
              day: 2,
              start: 15.25,
              finish: 16.25,
              weeks: [9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21],
              type: 'Stream',
              online: false,
              subjectCode: 'MAST20004',
              codes: ['MAST20004/U/1/SM1/L02/02'],
              locations: ['PAR-Redmond Barry-101 (Lyle Theatre)'],
              classCode: {
                number: 2,
                type: 'L',
              },
              streamNumber: 2,
            },
            {
              description: 'Lecture 3',
              day: 4,
              start: 15.25,
              finish: 16.25,
              weeks: [9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21],
              type: 'Stream',
              online: false,
              subjectCode: 'MAST20004',
              codes: ['MAST20004/U/1/SM1/L03/02'],
              locations: ['PAR-Redmond Barry-101 (Lyle Theatre)'],
              classCode: {
                number: 3,
                type: 'L',
              },
              streamNumber: 2,
            },
          ],
          streamNumbers: [2],
        },
        {
          type: 'L',
          classes: [
            {
              description: 'Lecture 1',
              day: 0,
              start: 9,
              finish: 10,
              weeks: [9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21],
              type: 'Stream',
              online: false,
              subjectCode: 'MAST20004',
              codes: ['MAST20004/U/1/SM1/L01/01'],
              locations: ['PAR-Redmond Barry-101 (Lyle Theatre)'],
              classCode: {
                number: 1,
                type: 'L',
              },
              streamNumber: 1,
            },
            {
              description: 'Lecture 2',
              day: 2,
              start: 9,
              finish: 10,
              weeks: [9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21],
              type: 'Stream',
              online: false,
              subjectCode: 'MAST20004',
              codes: ['MAST20004/U/1/SM1/L02/01'],
              locations: ['PAR-Redmond Barry-101 (Lyle Theatre)'],
              classCode: {
                number: 2,
                type: 'L',
              },
              streamNumber: 1,
            },
            {
              description: 'Lecture 3',
              day: 4,
              start: 11,
              finish: 12,
              weeks: [9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21],
              type: 'Stream',
              online: false,
              subjectCode: 'MAST20004',
              codes: ['MAST20004/U/1/SM1/L03/01'],
              locations: ['PAR-Redmond Barry-101 (Lyle Theatre)'],
              classCode: {
                number: 3,
                type: 'L',
              },
              streamNumber: 1,
            },
          ],
          streamNumbers: [1],
        },
      ],
      type: 'L',
      name: 'Lecture',
    },
    {
      streams: [
        {
          type: 'P',
          classes: [
            {
              description: 'Practical 1',
              day: 4,
              start: 12,
              finish: 13,
              weeks: [9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21],
              type: 'Stream',
              online: false,
              subjectCode: 'MAST20004',
              codes: ['MAST20004/U/1/SM1/P01/22'],
              locations: ['PAR-Peter Hall-G50'],
              classCode: {
                number: 1,
                type: 'P',
              },
              streamNumber: 22,
            },
            {
              description: 'Practical 2',
              day: 4,
              start: 13,
              finish: 14,
              weeks: [9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21],
              type: 'Stream',
              online: false,
              subjectCode: 'MAST20004',
              codes: ['MAST20004/U/1/SM1/P02/22'],
              locations: ['PAR-Peter Hall-G69 (Thompson Lab)'],
              classCode: {
                number: 2,
                type: 'P',
              },
              streamNumber: 22,
            },
          ],
          streamNumbers: [22],
        },
        {
          type: 'P',
          classes: [
            {
              description: 'Practical 1',
              day: 4,
              start: 12,
              finish: 13,
              weeks: [9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21],
              type: 'Stream',
              online: false,
              subjectCode: 'MAST20004',
              codes: ['MAST20004/U/1/SM1/P01/21'],
              locations: ['PAR-Peter Hall-G09 (Classroom D)'],
              classCode: {
                number: 1,
                type: 'P',
              },
              streamNumber: 21,
            },
            {
              description: 'Practical 2',
              day: 4,
              start: 13,
              finish: 14,
              weeks: [9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21],
              type: 'Stream',
              online: false,
              subjectCode: 'MAST20004',
              codes: ['MAST20004/U/1/SM1/P02/21'],
              locations: ['PAR-Peter Hall-G69 (Thompson Lab)'],
              classCode: {
                number: 2,
                type: 'P',
              },
              streamNumber: 21,
            },
          ],
          streamNumbers: [21],
        },
        {
          type: 'P',
          classes: [
            {
              description: 'Practical 1',
              day: 4,
              start: 9,
              finish: 10,
              weeks: [9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21],
              type: 'Stream',
              online: false,
              subjectCode: 'MAST20004',
              codes: ['MAST20004/U/1/SM1/P01/08', 'MAST20004/U/1/SM1/P01/07'],
              locations: ['PAR-Peter Hall-G50', 'PAR-Peter Hall-G10'],
              classCode: {
                number: 1,
                type: 'P',
              },
              streamNumber: 8,
            },
            {
              description: 'Practical 2',
              day: 4,
              start: 10,
              finish: 11,
              weeks: [9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21],
              type: 'Stream',
              online: false,
              subjectCode: 'MAST20004',
              codes: ['MAST20004/U/1/SM1/P02/08', 'MAST20004/U/1/SM1/P02/07'],
              locations: ['PAR-Peter Hall-G69 (Thompson Lab)'],
              classCode: {
                number: 2,
                type: 'P',
              },
              streamNumber: 8,
            },
          ],
          streamNumbers: [8, 7],
        },
        {
          type: 'P',
          classes: [
            {
              description: 'Practical 1',
              day: 3,
              start: 15.25,
              finish: 16.25,
              weeks: [9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21],
              type: 'Stream',
              online: false,
              subjectCode: 'MAST20004',
              codes: ['MAST20004/U/1/SM1/P01/20', 'MAST20004/U/1/SM1/P01/19'],
              locations: ['PAR-Peter Hall-G50', 'PAR-Peter Hall-G10'],
              classCode: {
                number: 1,
                type: 'P',
              },
              streamNumber: 20,
            },
            {
              description: 'Practical 2',
              day: 3,
              start: 16.25,
              finish: 17.25,
              weeks: [9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21],
              type: 'Stream',
              online: false,
              subjectCode: 'MAST20004',
              codes: ['MAST20004/U/1/SM1/P02/20', 'MAST20004/U/1/SM1/P02/19'],
              locations: ['PAR-Peter Hall-G69 (Thompson Lab)'],
              classCode: {
                number: 2,
                type: 'P',
              },
              streamNumber: 20,
            },
          ],
          streamNumbers: [20, 19],
        },
        {
          type: 'P',
          classes: [
            {
              description: 'Practical 1',
              day: 3,
              start: 13.25,
              finish: 14.25,
              weeks: [9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21],
              type: 'Stream',
              online: false,
              subjectCode: 'MAST20004',
              codes: ['MAST20004/U/1/SM1/P01/18', 'MAST20004/U/1/SM1/P01/17'],
              locations: ['PAR-Peter Hall-G09 (Classroom D)', 'PAR-Peter Hall-G50'],
              classCode: {
                number: 1,
                type: 'P',
              },
              streamNumber: 18,
            },
            {
              description: 'Practical 2',
              day: 3,
              start: 14.25,
              finish: 15.25,
              weeks: [9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21],
              type: 'Stream',
              online: false,
              subjectCode: 'MAST20004',
              codes: ['MAST20004/U/1/SM1/P02/18', 'MAST20004/U/1/SM1/P02/17'],
              locations: ['PAR-Peter Hall-G69 (Thompson Lab)'],
              classCode: {
                number: 2,
                type: 'P',
              },
              streamNumber: 18,
            },
          ],
          streamNumbers: [18, 17],
        },
        {
          type: 'P',
          classes: [
            {
              description: 'Practical 1',
              day: 3,
              start: 11,
              finish: 12,
              weeks: [9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21],
              type: 'Stream',
              online: false,
              subjectCode: 'MAST20004',
              codes: ['MAST20004/U/1/SM1/P01/16', 'MAST20004/U/1/SM1/P01/15'],
              locations: ['PAR-Peter Hall-G50', 'PAR-Peter Hall-G09 (Classroom D)'],
              classCode: {
                number: 1,
                type: 'P',
              },
              streamNumber: 16,
            },
            {
              description: 'Practical 2',
              day: 3,
              start: 12,
              finish: 13,
              weeks: [9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21],
              type: 'Stream',
              online: false,
              subjectCode: 'MAST20004',
              codes: ['MAST20004/U/1/SM1/P02/16', 'MAST20004/U/1/SM1/P02/15'],
              locations: ['PAR-Peter Hall-G69 (Thompson Lab)'],
              classCode: {
                number: 2,
                type: 'P',
              },
              streamNumber: 16,
            },
          ],
          streamNumbers: [16, 15],
        },
        {
          type: 'P',
          classes: [
            {
              description: 'Practical 1',
              day: 3,
              start: 9,
              finish: 10,
              weeks: [9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21],
              type: 'Stream',
              online: false,
              subjectCode: 'MAST20004',
              codes: ['MAST20004/U/1/SM1/P01/14', 'MAST20004/U/1/SM1/P01/13'],
              locations: ['PAR-Peter Hall-G09 (Classroom D)', 'PAR-Peter Hall-G50'],
              classCode: {
                number: 1,
                type: 'P',
              },
              streamNumber: 14,
            },
            {
              description: 'Practical 2',
              day: 3,
              start: 10,
              finish: 11,
              weeks: [9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21],
              type: 'Stream',
              online: false,
              subjectCode: 'MAST20004',
              codes: ['MAST20004/U/1/SM1/P02/14', 'MAST20004/U/1/SM1/P02/13'],
              locations: ['PAR-Peter Hall-G69 (Thompson Lab)'],
              classCode: {
                number: 2,
                type: 'P',
              },
              streamNumber: 14,
            },
          ],
          streamNumbers: [14, 13],
        },
        {
          type: 'P',
          classes: [
            {
              description: 'Practical 1',
              day: 2,
              start: 13.25,
              finish: 14.25,
              weeks: [9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21],
              type: 'Stream',
              online: false,
              subjectCode: 'MAST20004',
              codes: ['MAST20004/U/1/SM1/P01/23'],
              locations: ['PAR-Peter Hall-G50'],
              classCode: {
                number: 1,
                type: 'P',
              },
              streamNumber: 23,
            },
            {
              description: 'Practical 2',
              day: 2,
              start: 14.25,
              finish: 15.25,
              weeks: [9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21],
              type: 'Stream',
              online: false,
              subjectCode: 'MAST20004',
              codes: ['MAST20004/U/1/SM1/P02/23'],
              locations: ['PAR-Peter Hall-G69 (Thompson Lab)'],
              classCode: {
                number: 2,
                type: 'P',
              },
              streamNumber: 23,
            },
          ],
          streamNumbers: [23],
        },
        {
          type: 'P',
          classes: [
            {
              description: 'Practical 1',
              day: 2,
              start: 11,
              finish: 12,
              weeks: [9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21],
              type: 'Stream',
              online: false,
              subjectCode: 'MAST20004',
              codes: ['MAST20004/U/1/SM1/P01/12', 'MAST20004/U/1/SM1/P01/11'],
              locations: ['PAR-Peter Hall-G50', 'PAR-Peter Hall-G09 (Classroom D)'],
              classCode: {
                number: 1,
                type: 'P',
              },
              streamNumber: 12,
            },
            {
              description: 'Practical 2',
              day: 2,
              start: 12,
              finish: 13,
              weeks: [9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21],
              type: 'Stream',
              online: false,
              subjectCode: 'MAST20004',
              codes: ['MAST20004/U/1/SM1/P02/12', 'MAST20004/U/1/SM1/P02/11'],
              locations: ['PAR-Peter Hall-G69 (Thompson Lab)'],
              classCode: {
                number: 2,
                type: 'P',
              },
              streamNumber: 12,
            },
          ],
          streamNumbers: [12, 11],
        },
        {
          type: 'P',
          classes: [
            {
              description: 'Practical 1',
              day: 1,
              start: 14.25,
              finish: 15.25,
              weeks: [9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21],
              type: 'Stream',
              online: false,
              subjectCode: 'MAST20004',
              codes: ['MAST20004/U/1/SM1/P01/10', 'MAST20004/U/1/SM1/P01/09'],
              locations: ['PAR-Peter Hall-G09 (Classroom D)', 'PAR-Peter Hall-G50'],
              classCode: {
                number: 1,
                type: 'P',
              },
              streamNumber: 10,
            },
            {
              description: 'Practical 2',
              day: 1,
              start: 15.25,
              finish: 16.25,
              weeks: [9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21],
              type: 'Stream',
              online: false,
              subjectCode: 'MAST20004',
              codes: ['MAST20004/U/1/SM1/P02/10', 'MAST20004/U/1/SM1/P02/09'],
              locations: ['PAR-Peter Hall-G69 (Thompson Lab)'],
              classCode: {
                number: 2,
                type: 'P',
              },
              streamNumber: 10,
            },
          ],
          streamNumbers: [10, 9],
        },
        {
          type: 'P',
          classes: [
            {
              description: 'Practical 1',
              day: 1,
              start: 9,
              finish: 10,
              weeks: [9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21],
              type: 'Stream',
              online: false,
              subjectCode: 'MAST20004',
              codes: ['MAST20004/U/1/SM1/P01/06', 'MAST20004/U/1/SM1/P01/05'],
              locations: ['PAR-Peter Hall-G50', 'PAR-Peter Hall-G10'],
              classCode: {
                number: 1,
                type: 'P',
              },
              streamNumber: 6,
            },
            {
              description: 'Practical 2',
              day: 1,
              start: 10,
              finish: 11,
              weeks: [9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21],
              type: 'Stream',
              online: false,
              subjectCode: 'MAST20004',
              codes: ['MAST20004/U/1/SM1/P02/06', 'MAST20004/U/1/SM1/P02/05'],
              locations: ['PAR-Peter Hall-G69 (Thompson Lab)'],
              classCode: {
                number: 2,
                type: 'P',
              },
              streamNumber: 6,
            },
          ],
          streamNumbers: [6, 5],
        },
        {
          type: 'P',
          classes: [
            {
              description: 'Practical 1',
              day: 0,
              start: 12,
              finish: 13,
              weeks: [9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21],
              type: 'Stream',
              online: false,
              subjectCode: 'MAST20004',
              codes: ['MAST20004/U/1/SM1/P01/04', 'MAST20004/U/1/SM1/P01/03'],
              locations: ['PAR-Peter Hall-G50', 'PAR-Peter Hall-G09 (Classroom D)'],
              classCode: {
                number: 1,
                type: 'P',
              },
              streamNumber: 4,
            },
            {
              description: 'Practical 2',
              day: 0,
              start: 13,
              finish: 14,
              weeks: [9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21],
              type: 'Stream',
              online: false,
              subjectCode: 'MAST20004',
              codes: ['MAST20004/U/1/SM1/P02/04', 'MAST20004/U/1/SM1/P02/03'],
              locations: ['PAR-Peter Hall-G69 (Thompson Lab)'],
              classCode: {
                number: 2,
                type: 'P',
              },
              streamNumber: 4,
            },
          ],
          streamNumbers: [4, 3],
        },
        {
          type: 'P',
          classes: [
            {
              description: 'Practical 1',
              day: 0,
              start: 10,
              finish: 11,
              weeks: [9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21],
              type: 'Stream',
              online: false,
              subjectCode: 'MAST20004',
              codes: ['MAST20004/U/1/SM1/P01/02', 'MAST20004/U/1/SM1/P01/01'],
              locations: ['PAR-Peter Hall-G50', 'PAR-Peter Hall-G10'],
              classCode: {
                number: 1,
                type: 'P',
              },
              streamNumber: 2,
            },
            {
              description: 'Practical 2',
              day: 0,
              start: 11,
              finish: 12,
              weeks: [9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21],
              type: 'Stream',
              online: false,
              subjectCode: 'MAST20004',
              codes: ['MAST20004/U/1/SM1/P02/02', 'MAST20004/U/1/SM1/P02/01'],
              locations: ['PAR-Peter Hall-G69 (Thompson Lab)'],
              classCode: {
                number: 2,
                type: 'P',
              },
              streamNumber: 2,
            },
          ],
          streamNumbers: [2, 1],
        },
      ],
      type: 'P',
      name: 'Practical',
    },
  ],
  _weirdStreamContainers: [],
  _weekendClasses: false,
};
